### ISSUE TITLE
Add box button should stay at the same position as boxes continue to get closed and added

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#107]
Saw the demo on Pulkit's screen where after closing boxes, the Add box button keeps moving down. The correct behavior  is for that button to always stay in the same position, with an open box on top and all the closed boxes below it.

**Comment by ayushranjan-planetria** [comment]
Hi @pulkitsinghal , I have fixed the issue and created PR, please review, thanks.
cc @srisub
