### ISSUE TITLE
Sanity test on mgr report: order qty isn't calc properly [DSL - QOH]. If Order Qty is zero or -ve don't show those in the manager report

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#137]

**Comment by pulkitsinghal** [comment]
@elbrando - if a report is pulling something like negative numbers in QOH from Vend, what action would you like me to take "process-wise" other than what you already see on this snapshot?
<img width="590" alt="screen shot 2015-07-11 at 4 37 08 pm" src="https://cloud.githubusercontent.com/assets/821963/8635533/479d714a-27ec-11e5-8831-166f0b5761ec.png">

**Comment by pulkitsinghal** [comment]
@srisub - fixed the calculation, there is a minor open question for @elbrando but regardless, you can still test and verify that we perform the calculation as `[DSL - QOH]`

**Comment by pulkitsinghal** [comment]
Closing this, we can open a new one based on feedback.
