### ISSUE TITLE
Update Vend's DSL once row is edited

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#138]
Desired Stock Level in warehouse [get mapped to](https://github.com/ShoppinPal/warehouse-manager-generate-stock-order/blob/774772bed38f001a3ee0c2d12a57be669246b838/jobs/generate-stock-order.js#L89) the `reorder_point` field in Vend ... it is the level that stock must get to before Vend identifies it as 'low stock'

**Comment by pulkitsinghal** [comment]
resolved by https://github.com/ShoppinPal/warehouse/commit/2f277893a2336b1f2dedb4f58946c42b21590a6b
