### ISSUE TITLE
Swipe to rename report on store landing not working selectively for CSC reports

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#150]
Steps to reproduce: 
1) Logged in with Reno credential and clicked around on store landing top filter buttons  
2) Now for the first 4 reports I'm unable to swipe and rename. 

@pulkitsinghal could it be because of the mongo switch? @ayushranjan-planetria please take a look once you are done with Show More.

**Comment by ayushranjan-planetria** [comment]
Hi @srisub , those reports are not editable because they do not have 'manager' state, see related issue https://github.com/ShoppinPal/warehouse/issues/116. Plz let me know if any change is required.
cc @pulkitsinghal

**Comment by srisub** [comment]
Found out from @pulkitsinghal that these are corrupt reports and not a real issue so I'm closing this
