### ISSUE TITLE
Case Quantities

### ISSUE THREAD

**Issue by elbrando** [ShoppinPal/warehouse#157]
For product that can only be ordered in specific quantities, or cases, use CQ - ### as a tag to specify for Managers ReOrder Report to fill in the Order Quantity. For these and only these products, this process replaces the regular process of DSL - QOH = OQ

We need to populate the order with only that amount or multiples of that amount. So for something that can only be ordered as a box of 20 if we determine only 5 more are needed, you can only order it as 20 or its multiples 40, 60 etc.

Would be nice to have in the UI a way to clearly show that the item is ordered in the specific qty.

**Comment by pulkitsinghal** [comment]
@elbrando - close it if it does what you need, otherwise assign it back to me with instructions

**Comment by elbrando** [comment]
Looking great. Good work.
