### ISSUE TITLE
Store report edit mode issues 

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#16]
@Chhaya-rai I noticed a few issues while playing around with the store page on staging. 

1) Doesn't match up to the final design:
a) need to show all the data in the row when in edit mode, not just the editable fields. 
b) vitural keyboard doesn't show up.  
c) Comments as they are edited show up in an additional view on top, let's not have it this way, its seems like another row and there's no need to show it in 2 places. 
d) Top button should say Review and Submit isntead of Submit to Warehouse.  

cc @pulkitsinghal

**Comment by Chhaya-rai** [comment]
@srisub worked on above issues and fixed 
a) Comments page issues resolved.
b) view updated with new design.
c)top button changed as Review and Submit

working on
a) Virtual keyboard .

**Comment by srisub** [comment]
@Chhaya-rai 
1) please switch the plus and minus placement, minus button should be on the left of the number. 
2) we shouldn't allow quantities to go negative. once it reaches zero let's disable the minus.
3) I was hoping that clicking anywhere outside the dark blue area will take you out of edit mode, for e.g. if you clicked on the rows below. However it only happens if you put cursor in the white area outside the table. 
4) As mentioned in https://github.com/ShoppinPal/warehouse/issues/19 use full names for column titles. Also change Submit to Review. 
5) Review screen should only allow editing Order Quantity, comment and D.S. Level should be read-only. On the review screen have a Submit button which then submits to warehouse and changes state in the backend. 
6) Fix Jump To bug

**Comment by pulkitsinghal** [comment]
@srisub - why was this closed, were new opens opened, was it resolved? Where are the checkins? etc. etc.

**Comment by srisub** [comment]
@pulkitsinghal yes to my knowledge everything is fixed except 3, for which we have a new issue on Edit. 4 and 5 are not relevant anymore given Brandon's input of not needing a Review screen any more.

**Comment by srisub** [comment]
I know that we don't have the commits mentioned, I'm just going by what I see in staging

**Comment by pulkitsinghal** [comment]
@developers let's mention the issue we are working on in our Checkins or PR merge messages so it's auto tracked here too
