### ISSUE TITLE
If manager deletes a row, DSL should still be saved

### ISSUE THREAD

**Issue by pulkitsinghal** [ShoppinPal/warehouse#167]
The following UX is less than ideal:
1. Manager edits a row and changes the DSL of a product to zero
2. dismisses the editable row by clicking outside (UI saved the altered values such as DSL)
3. Manager opens the editable row again and now clicks the delete button

Instead it should work as follows:
1. Manager edits a row and changes the DSL of a product to zero
2. Manager click delete (the delete op should check for any data changes and persist them, despite the fact that deletion is happening)

cc @elbrando

**Comment by pulkitsinghal** [comment]
@elbrando - if it works as expected, please close it

**Comment by elbrando** [comment]
Seems to be working.
