### ISSUE TITLE
Add configuration to support worker oriented instances

### ISSUE THREAD

**Issue by pulkitsinghal** [ShoppinPal/warehouse#187]
The `devops` team will configure two types of services: `web` and `worker`

One will be responsible for servicing requests coming from browsers.

Another will be responsible for servicing requests coming from workers.

If the load-balancer cannot be configured to auto-route the worker requests to the `worker` service based on IP ... then we will need to add configuration similar to `site.baseUrl` that tracks `site.workerServiceUrl` ... this will also require code changes to use the new `site.workerServiceUrl` when creating worker payload instead of the older `site.baseUrl`

Check with `devops` team to see how their research & experimentation progress to determine if this additional work is required or not.

**Comment by pulkitsinghal** [comment]
@harshadyeola - please fill in your remarks about the implementation and architecture that was used in this topic and then close it out.

**Comment by harshadyeola** [comment]
Implementation consists of 2 services with same docker images running 
1. Front-end traffic
2. Worker Traffic
Traffic is distributed depending on the source IP of request (achieved via NGINX map feature)
This architecture has following pro's :
- even on crash of web(frontend) the worker container will not affect as it is running as seperate service.
