### ISSUE TITLE
Add CircleCI based automation for this project

### ISSUE THREAD

**Issue by pulkitsinghal** [ShoppinPal/warehouse#200]

**Comment by harshadyeola** [comment]
@pulkitsinghal 
This is almost finished. Waiting for tests to be finished.

**Comment by pulkitsinghal** [comment]
There won't be any tests for quite some time it seems. But there will be several releases before that. So I suppose the prudent course of action is to finish this up here and let this automation help in the build and deployment of upcoming releases.

Testing will have to be manual until then.

Let's close this out and we can open a new issue for supporting tests in a month or two from now when they are available.

**Comment by harshadyeola** [comment]
Understood! will do it that way.

**Comment by harshadyeola** [comment]
I'll close this issue as this project is integrated with circleci.
