### ISSUE TITLE
Cannot dismiss Edit box

### ISSUE THREAD

**Issue by elbrando** [ShoppinPal/warehouse#22]
On iPad, after left swipe on product, edit box won't collapse back down upon deselection. Edit should close/collapse back to line item to allow for right swipe or edit of other product.

**Comment by Chhaya-rai** [comment]
@srisub , @shridharmalagi  
Bug fixed and raised pull request 
https://github.com/ShoppinPal/warehouse/pull/38
Note: Edit mode will dismiss whenever user move out of edit mode.

**Comment by srisub** [comment]
@pulkitsinghal @ayushranjan-planetria for the edit mode feedback from Brandon "edit rows don't collapse anymore without opening another editable row" I am using this existing issue which Chhaya attempted to fix but the issue persists

**Comment by pulkitsinghal** [comment]
Research Summary: ng-mouseleave does not work for "tr", only for "td" ... and even then it works very poorly for touch events in iOS

* http://stackoverflow.com/questions/26162805/ng-click-not-firing-when-using-ng-mouseenter-or-ng-mouseover-on-tablet
  * http://sitr.us/2011/07/28/how-mobile-safari-emulates-mouse-events.html
* https://docs.angularjs.org/api/ngTouch
  * https://docs.angularjs.org/api/ngTouch/service/$swipe
* http://stackoverflow.com/questions/24889411/what-is-the-touch-equivalent-to-mouseout-event
  * https://developer.mozilla.org/en-US/docs/Web/API/Touch_events
* http://stackoverflow.com/questions/4550427/prefered-alternative-to-onmouseover-for-touch
* http://quirksmode.org/mobile/tableTouch.html

**Comment by pulkitsinghal** [comment]
@ayushranjan-planetria - I forgot to say this earlier but you did a great thing here by replacing ng-show with ng-if the current number of watchers on this page went from approximately 12000 to 7658 .. good job :)

cc @srisub
