### ISSUE TITLE
Setup build environment on Google cloud 

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#25]
Questions for Google team: 
1) Ideal setup (any docs and best practices?) 
2) How to pick m/c spec
3) DN mapping

Next steps for Shridhar: 
- Secure jenkins so manual entry will require uname+pwd
- Setup auto deploy so jenkins pushes into staging as soon as code is committed

**Comment by pulkitsinghal** [comment]
@faisalrabbani took care of this
