### ISSUE TITLE
cli wizard revison 3

### ISSUE THREAD

**Issue by Bhushan001** [ShoppinPal/warehouse#277]
Need to make some improvements with the cli tool:

## Highest Priority

1. Script should explain and collect infor needed by `-e=terraform`
1. Update README instructions to kick off `-e=terraform` first then terraform script then `-e=web` then `-e=worker` then `-e=worker2`
1. When `-e=web` runs, it should always validate if key/value pairs that should have been terraform already are actually present, otherwise issue a warning where user can choose to exit or continue.
1. Same as above for `-e=worker` and `-e=worker2`

## Medium Priority

1. If key/secret used by terraform and the key/secret inside environment files when `-e=web` are the same ... then issue a warning before continuing.
    > WARNING: The key/secret are more powerful than they need to be. Everything will work but ideally we should automate the process and change this to use IAM acc based on AWS keys which has permissions like
    > - only put/post message on SQS queues that were generated
    > - and only read from the S3 bucket

## Low Priority
1. Validate if the key/secret provided for terraform has the appropriate permissions like create queue and create policy on queue
1. Make terraform script generate IAM acc based on AWS keys which has permissions like
    - only put/post message on SQS queues that were generated
    - and only read from the S3 bucket
    - don't forget to write them out to the environment files afterwards!

**Comment by pulkitsinghal** [comment]
@Bhushan001 - here's the recording with our discussion around these requirements and more:
https://drive.google.com/a/shoppinpal.com/file/d/1wD2dOlzriSNwp0lW9xn3JFfjufDuVMY3/view?usp=sharing

**Comment by yogesh8177** [comment]
Passing a powerful set of keys into terraform to generate a limited powered `iam` user was potentially dangerous and @harshadyeola92  recommended that we manually create such `iam` user and pass that `iam` user's key into `terraform.tfvars` file to generate sqs queues (edited)

Thus, terraform will populate the limited powered `iam` user's keys, sqs region and sqs url to `.env` and `worker.env`

**Comment by pulkitsinghal** [comment]
Most of this was handled by #285
