### ISSUE TITLE
Remove any & all jquery dependecies

### ISSUE THREAD

**Issue by pulkitsinghal** [ShoppinPal/warehouse#3]
@Chhaya-rai - if possible lets not use a separate jquery library with angular ... instead lets use the built-in jquery library inside angular: 
>  Does Angular use the jQuery library? 
> Yes, Angular can use jQuery if it's present in your app when the application is being bootstrapped. If jQuery is not present in your script path, Angular falls back to its own implementation of the subset of jQuery that we call jQLite.  Angular 1.3 only supports jQuery 2.1 or above. jQuery 1.7 and newer might work correctly with Angular but we don't guarantee that.

Here are some docs: https://docs.angularjs.org/api/ng/function/angular.element

**Comment by pulkitsinghal** [comment]
For example:

```
$.unique($scope.alphabets); // This method remove the duplicates from array
```
We can maybe look at angular alternatives like the `unique` filter etc. ... not sure

**Comment by pulkitsinghal** [comment]
This plunker will show you how to use the unique filter included in the Angular UI utilities to strip out duplicates in an object array. http://plnkr.co/edit/kxJFSw?p=preview

**Comment by Chhaya-rai** [comment]
Hi pulkit , 
i have removed the seprate jquery library , code clean-up done.
and also $.unique($scope.alphabets); has been removed from code instead using 'unique' filter.
code updated and pushed.
