### ISSUE TITLE
Abstract the header

### ISSUE THREAD

**Issue by pulkitsinghal** [ShoppinPal/warehouse#4]
The code for `<header class="header">/<header>` seems to have a lot in common everywhere. Abstract out this common functionality by either making it a directive or an html-view w/ ng-include for injection.

**Comment by pulkitsinghal** [comment]
@srisub - do you think this is frivolous? or at least last on the list of things todo for @Chhaya-rai?

**Comment by srisub** [comment]
@pulkitsinghal @Chhaya-rai I wouldn't call it frivolous but it is less imp than current to-dos for going live. It can continue to live in the backlog

**Comment by pulkitsinghal** [comment]
Well done @ayushranjan-planetria
