### ISSUE TITLE
New Stock Order fields

### ISSUE THREAD

**Issue by elbrando** [ShoppinPal/warehouse#43]
"Order From" is text. Needs to be populated dropdown of Suppliers

"Deliver To" is text. Needs to be populated dropdown of Outlets.

**Comment by Chhaya-rai** [comment]
@srisub @shridharmalagi @elbrando 

Bug fixed available in staging
https://warehouse-staging.shoppinpal.com/#/create-manual-order

**Comment by elbrando** [comment]
This link gives me a login but the login doesn't go anywhere. Is there a different link?

**Comment by pulkitsinghal** [comment]
@elbrando - it was fixed roughly 2-3 hours after you posted your last comment, the security has been changed up to use the username list provided by you. Please use the reno login.
