### ISSUE TITLE
Store manager workflow + changes to store landing 

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#45]
When a store manager logs in, always go to the store landing page:
https://www.dropbox.com/s/t4ju0wdp53a4tja/2.0-store-landing.jpg?dl=0

Don't use the current one which shows 2-col list view for new orders and ones in process. Secondly, we need to use the filters 'New Orders', 'In Process' and 'Receive', i.e. get rid of 'Fulfill' from the store manager's landing. 

On left swipe, Order name should be editable. Behavior can be same as how we add comments inside the report. 

Workflow: on Submit from store manager report (last step),  show spinner/popup "Your order has been submitted for fulfillment." then go to landing page

Add 'Create Manual Order' button similar to what we have for warehouse landing 

@pulkitsinghal I've created a separate issue to track the auto generation of report ID: https://github.com/ShoppinPal/warehouse/issues/56

Note: the login creds are the same for store manager and the receiver.

**Comment by pulkitsinghal** [comment]
@srisub - that snapshot URL is quite different from the design here: https://github.com/ShoppinPal/warehouse/issues/49

Just want to make sure that you clarify in comments so there isn't any accidental duplicate work for @Chhaya-rai
