### ISSUE TITLE
Store landing backend - auto generate Order ID 

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#56]
As discussed few weeks back we need a system generated ID that will show up on the store landing and persist across all screens in the workflow. @elbrando did not have another specific requirements other than what he said in his requirments doc
"Reference # Assigned (by software). Need to show this on all the report screens."

**Comment by pulkitsinghal** [comment]
If it doesn't have to be editable then does that mean what's present currently in staging suffices?

![screen shot 2015-05-25 at 6 44 46 am](https://cloud.githubusercontent.com/assets/821963/7796851/908f2fc8-02a9-11e5-8cc5-e63fb2ea88b4.png)
