### ISSUE TITLE
Import functionality (to be used from Create Manual Order and warehouse landing)

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#57]
Discussed offline with @Chhaya-rai

**Comment by pulkitsinghal** [comment]
I'm working wiring up the form fields for the page first.

**Comment by pulkitsinghal** [comment]
@srisub - Just to be clear, the goal here is for us to add the functionality to:
* translate csv files into json
* then upload them using RESTful post requests from client side
* all the while displaying a progress bar

... correct?

**Comment by srisub** [comment]
Correct. Don’t forget to show the file selector pop up before all of this and keep reminding yourself that this always will happen on a powerful desktop :)

**Comment by pulkitsinghal** [comment]
Surprisingly it seems that client side creation of rows is what will end up locking the UI, if I can't improve upon this [commit](https://github.com/ShoppinPal/warehouse/commit/881e561fa0b03804785cf61fbd0c509a4296badb) I may change the approach and move the work to be server-side/queue-worker-based.

**Comment by pulkitsinghal** [comment]
The folks over at strongloop support gave me some clues:
https://github.com/strongloop/loopback-sdk-angular/issues/122
https://github.com/strongloop/loopback-sdk-angular/pull/138

So basically the `createMany()` method (for angular) should be available anytime now ... they just need to accept the community member's pull request.

**Comment by srisub** [comment]
Coolness!

**Comment by pulkitsinghal** [comment]
Just need to wait for the loopback PR to get done

**Comment by pulkitsinghal** [comment]
Wanted to leverage latest changes to angular SDK strongloop/loopback-sdk-angular#138 and finish up #57 ... but loopback freezes after the POSTs happen so need to go analyze that now.

**Comment by pulkitsinghal** [comment]
@srisub: So I was demoing the feature to @elbrando before merging and apparently I had the use case all wrong and the difference (in what I thought the input was and what it actually is) ... is quite significant. So I will be restarting this task from scratch and performing it on the server side. So if you can revive your file upload + loopback storage expertise to give me a quick tutorial, please do so, otherwise I'll just learn it from the docs.

**Comment by pulkitsinghal** [comment]
Here's the new plan:
1. Leverage loopback's ability to upload a file
2. Submit meta info about CSV file to a worker
3. Write a basic worker that can use the meta info about the file to download it from loopback
4. Expand the worker to do all the same things as https://github.com/ShoppinPal/warehouse-manager-generate-stock-order with the followign exceptions:
  1. report state should be set such that it ready to be received
  2. products should be filtered based on SKUs from the CSV file
  3. lineitem `state` should be set as `boxed`
  4. lineitem `quantityOnHand` and `productId` should be set based on the data fetched from Vend
  5. lineitem `supplyCost` and `orderQuantity` should be set based on values from the CSV file

**Comment by pulkitsinghal** [comment]
What's remaining at this point in time?
1. Need to create an equivalent consignment in Vend for the imported report with its status preset and then changed from OPEN to SENT automagically.
1. Should we have a separate UI page for file imports so that its not mish-mashed with the UX for the generate stock order flow?
1. What sort of pre-validations check should be performed on the client-side for the CSV file to be imported? What is the cost of floating errors from the server side to display on the client instead? Is that even possible?
1. Should there be any extra steps around SKUs that aren't present in Vend?
1. Should there be any extra steps around products that don't have a department/product-type assigned to them? Having these absent does mess with the UI in warehouse a little but what kind of fixes (programmatic vs. administrative) is this impact worth? That's something to ponder.

**Comment by pulkitsinghal** [comment]
@elbrando - ready for testing by you

**Comment by pulkitsinghal** [comment]
[2:37 PM] Brandon Lehman: Can I get a generic warehouse login ASAP using usernameX and passwordB?
[2:40 PM] Brandon Lehman: OK, @pulkit, I imported Skelly Gift Shop. Got some issues. Can the "Order Name" be changed to not be the filename? Also, the "boxed" products section has blanks for "fulfilled qty".
[3:56 PM] Brandon Lehman: Also, "boxed" isn't grouped but has group headers. Not a biggie.

----

[4:29 PM] Pulkit Singhal:
1. let me see what i can do about new login
2. order name is one of those things that would take a week to put it! I know ! Ridiculous but that's how lacking the docs on coding side are for including metadata with file uploads ... So how about we circumvent for now with you changing the order name directly via mongodb after u create it? If there is a better suited name that I can generate for the order that can be BASED off the info in the file name then do let me know
3. the missing fulfilled qty values in the boxed section is a bug that I suspect has been around for quite some time but simply escaped our notice till now, will confirm after running some tests
4. same thoughts around group headers which aren't grouped in the boxed section ... It's been around and probably afflicts the non-imported workflow as well but need to spend some time testing to confirm before I dive into the fix

**Comment by pulkitsinghal** [comment]
* [Aug-21 12:40 PM] Brandon Lehman: "Generating...you may tap to check status every few minutes." doesn't work. The page has to be reloaded to update the status.
* [Aug-21 1:33 PM] Brandon Lehman: imported orders are disappearing from the store's landing page after they have finished generating.

  ```
[Aug-21 1:38 PM] Pulkit Singhal: that's because there was an understanding that if something is in a warehouse queue then manager cannot see it ...
[Aug-21 1:40 PM] Brandon Lehman: FYI, it shows up in Skelly landing page while "generating" That's why I thought it was disappearing.
[Aug-21 1:41 PM] Pulkit Singhal: ah good point ... i need to take that into account for UX and think of something ... no clue how right now but i have to come up with something
  ```
* [Aug-21 1:40 PM] Brandon Lehman: We also need a way to delete these from here/warehouse side.

  ```
[Aug-21 1:42 PM] Brandon Lehman: Delete these old, "bad" orders. If we are forcing warehouse staff to regenerate order if there are incorrectly setup products (product type, not found, etc.), then they have to fix and redo the order again. That means they have to get rid of these old, "bad" ones.
[Aug-21 1:42 PM] Brandon Lehman: I can't be doing in RoboMongo all the time.
[Aug-21 1:52 PM] Brandon Lehman: "fixing" incorrect product that shows up after import and then doing it again works great. Now, if we could just delete the bad one we would be golden.
  ```

* There is a lag while the rows are being populated in Vend after warehouse reviews and submits them. Should there be a state between `warehouse_fulfill` and `mangaer_receive` during which neither party is allowed to drill down or work with that report but is clearly informed that its in the works?

  ```
[Aug-21 1:51 PM] Brandon Lehman: @pulkit Closed boxes and submitted as Fulfilled but it's not changed status. Does that take a while?
[Aug-21 1:52 PM] Pulkit Singhal: so 200 rows means at least 400 seconds ... understood on the delete front
[Aug-21 1:53 PM] Brandon Lehman: 119 rows, so just under 6 minutes.
  ```

* [Aug-21 3:18 PM] Brandon Lehman: OK. I'll check in with you later. Can you delete those for me?

* [Aug-21 8:02 PM] Pulkit Singhal: i submitted 419 rows but vend got 421 ... 

  ```
[Aug-21 8:17 PM] Pulkit Singhal: there are only 419 rows in the DB so something got sent twice ... might be a fundamental tcp/ip retry problem with nodejs ... don't know right now
[Aug-21 8:23 PM] Brandon Lehman: Well, the header row doesn't count with the DB and the last item, s-101 is special tag they send but isn't in Vend. So, those two could be your difference.
[Aug-21 8:24 PM] Pulkit Singhal: see if it was 421 row in db and 419 in vend i could live with that but its 421 rows in vend and 419 in DB ... how is that even possible ... data flows from db to vend ... so something is duplicated
[Aug-21 8:25 PM] Brandon Lehman: Oh, 421 in *Vend*. That makes it worse.
[Aug-21 8:26 PM] Pulkit Singhal: here's id for the cancelled report: 47fe23b6-28bf-11e5-f4e4-4867246d54e9 ... it says: "DISPLAYING 401 TO 421 OF 421."
[Aug-21 8:27 PM] Brandon Lehman: Gotcha ... Sort by SKU and your first result, 10078, is a dupe.
[Aug-21 8:44 PM] Brandon Lehman: So, exported the order. It's 422 with that one duplicate being the only extra thing in it. I noticed it had a 0 in the ORDER column while all the rest are blank/null.
  ```
