### ISSUE TITLE
Virtual keyboard should pop up ONLY on iPad  

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#60]
Desktop users should be allowed to use their normal keyboard, DO NOT pop the virtual keyboard outside of the iPad form factor.

**Comment by Chhaya-rai** [comment]
@srisub  @shridharmalagi  Device detector added , issues fixed

**Comment by pulkitsinghal** [comment]
After comparing the logs for various devices, I came to the conclusion that it is better to show keyboard when device is know to be iPad and everything else can just skip the virtual keyboard.

[detect.iphone.log | uploaded via ZenHub](https://files.zenhub.io/5565f2ad2e40c2a00a5d6fd5)

[detect.ipad.log | uploaded via ZenHub](https://files.zenhub.io/5565f2ad2e40c2a00a5d6fd4)

[detect.mac.log | uploaded via ZenHub](https://files.zenhub.io/5565f2ad2e40c2a00a5d6fd6)

**Comment by ayushranjan-planetria** [comment]
Hi @pulkitsinghal , the issue should be fixed now as we are using device instead of OS for detection as per your suggestion, please review, thanks.
cc @srisub

**Comment by pulkitsinghal** [comment]
@srisub and or @elbrando - please close it after testing to your satisfaction

**Comment by srisub** [comment]
Works fine
