### ISSUE TITLE
Removed unwanted quantity fields from store and warehouse review screens 

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#62]
For qty fields on review screens: store review scr will only have the order qty field with ability to edit via left swipe, and wareh review scr will similarly show and allow edit of the fulfilled qty. in the mocks it shows other qty fields also which you can ignore...

**Comment by Chhaya-rai** [comment]
@srisub Do i need to remove all the other field when user will left swipe or in edit mode , only order qty should be visible other fields should not be visible. is my understanding correct on this issues ?

**Comment by srisub** [comment]
We don't need need a separate review screen anymore -- based on input from Brandon and @pulkitsinghal the Show Completed view will be used for review actions and top right button will do final submit. @elbrando do we need some type of warning pop when hitting the submit button? If so what would you like the message to say?

**Comment by elbrando** [comment]
"do we need some type of warning pop when hitting the submit button?"

I would say it should. It should say, "Your order has been submitted for fulfillment. Check back later for further status changes."

**Comment by pulkitsinghal** [comment]
ummm... although fair ... that's quite an assumption and I don't think we meant it that way
> We don't need need a separate review screen anymore
@elbrando - you okay with this?

**Comment by elbrando** [comment]
RE: separate review screen. 

My gut reaction is, "Of course we don't need a review screen now." But I could see the value in a Review that is identical, layout wise and data-ordering wise, before submitting. But there would have to be an "out" for the manager in case they noticed something wrong or wanted to change something. The "out" would go back to the original order but with their edited values. Then they change what needed to be changed but would have to swipe all other products to completed then review and submit again. That seems like bad juju. (Thus concludes my typing-out-loud).

I think, ideally, the "Show Completed" page would have sortable columns, including an "original data-order" sorting. If that's not possible, I still think we don't need the separate review page, for all the reasons above. It will just be an adjustment thing on the staff's part.
