### ISSUE TITLE
Virtual keyboard - on the active fields make it white and add cursor simulation 

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#75]

**Comment by ayushranjan-planetria** [comment]
Hi @srisub , updated the background color of the input field for virtual keyboard (currently coupled to the store-manager-report comment area), the cursor simulation also seems to work on iPad, please review issue (#75), PR-#84 , thanks.
cc @pulkitsinghal

**Comment by pulkitsinghal** [comment]
@srisub - the PR has been merged and should be available for testing at https://warehouse-staging.shoppinpal.com/ ... if you don't see the desired result then comment back otherwise close this after sufficient testing.

**Comment by srisub** [comment]
@ayushranjan-planetria as we saw, the cursor simulation didn't show on my version of Safari on the iPad. however the color contrast is enough as long as we can indicate focus on a field via the whitish color. I'll move this to the backlog for now and revisit based on @elbrando and his team's feedback
